### ISSUE TITLE
以导入私钥的方式创建ETH钱包，导出私钥报错

### ISSUE THREAD

**Issue by HowKeung** [consenlabs/token-core-android#20]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at org.consenlabs.tokencore.wallet.Wallet.exportPrivateKey(Wallet.java:91)
        at com.jungel.simple.MainActivity.onCreate(MainActivity.java:82)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by XuNeal** [comment]
麻烦贴一下相关代码的上下文

**Comment by HowKeung** [comment]
Wallet ethereumWallet = WalletManager.importWalletFromPrivateKey(new Metadata
                        (ChainType.ETHEREUM, Network.KOVAN, "ETH", ""),
                "dc1c142d2cce9847a0a7d7311fdfee6bfb3968c583f06a6bccadd3497eed3b25",
                "", true);

        Log.d(TAG, "ETH getAddress : " + ethereumWallet.getAddress());
        Log.d(TAG, "ETH getEncXPub : " + ethereumWallet.exportPrivateKey(""));//这行报错

**Comment by erichyx** [comment]
@allByWave 我这边也遇到一样的问题。

**Comment by XuNeal** [comment]
实在抱歉我刚刚测试了一下，发现是我们API设计忽略了一个必须参数。就是Metadata.source参数。这个其实是必选的，但是并未在构造方法中体现出来。实在抱歉
你可以测试一下代码：

```
 @Test
  public void testExportAddress() {
    Metadata metadata = new Metadata(ChainType.ETHEREUM, Network.KOVAN, "ETH", "");
    metadata.setSource(Metadata.FROM_PRIVATE); // add set source. FROM_PRIVATE for ethereum, FROM_WIF for BTC single pk
    Wallet ethereumWallet = WalletManager.importWalletFromPrivateKey(metadata,
        "dc1c142d2cce9847a0a7d7311fdfee6bfb3968c583f06a6bccadd3497eed3b25",
        "", true);

    System.out.println("ETH getAddress : " + ethereumWallet.getAddress());
    System.out.println("ETH getEncXPub : " + ethereumWallet.exportPrivateKey(""));//这行报错
  }
```

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
