### ISSUE TITLE
导入eth keystore 报错

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#52]
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 268435468 byte allocation with 4194304 free bytes and 236MB until OOM
        at com.lambdaworks.crypto.SCrypt.scryptJ(SCrypt.java:93)
        at com.lambdaworks.crypto.SCrypt.scrypt(SCrypt.java:48)
        at org.consenlabs.tokencore.foundation.crypto.SCryptCrypto.generateDerivedKey(SCryptCrypto.java:41)
        at org.consenlabs.tokencore.foundation.crypto.Crypto.getValidDerivedKey(Crypto.java:128)
        at org.consenlabs.tokencore.foundation.crypto.Crypto.getCachedDerivedKey(Crypto.java:120)
        at org.consenlabs.tokencore.foundation.crypto.Crypto.verifyPassword(Crypto.java:100)
        at org.consenlabs.tokencore.wallet.keystore.Keystore.verifyPassword(Keystore.java:47)
        at org.consenlabs.tokencore.wallet.WalletManager.validateKeystore(WalletManager.java:388)
        at org.consenlabs.tokencore.wallet.WalletManager.importWalletFromKeystore(WalletManager.java:115)
        at com.uniplaza.wallet.repository.WalletRepository.lambda$importWalletByKeystore$8$WalletRepository(WalletRepository.java:435)
        at com.uniplaza.wallet.repository.WalletRepository$$Lambda$7.subscribe(Unknown Source)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:14409)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn.subscribeActual(FlowableObserveOn.java:56)
        at io.reactivex.Flowable.subscribe(Flowable.java:14409)
        at io.reactivex.Flowable.subscribe(Flowable.java:14356)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by lvshtwl** [comment]
提供keystore
{"address":"7663e2588aa696e23d97e259186c24e8f4a6df42","crypto":{"cipher":"aes-128-ctr","ciphertext":"aa1caf2704f72425daf2f3f856e33082f010375505c8514be5ecea6098a8ec02","cipherparams":{"iv":"111f0fb79b6bf9b74236fa3fe2627b3d"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"32675018cec6cb37657f9a5b77243e5c6e51864100be2576a28e691e01afc70f"},"mac":"e82043f9917b88dab3ee53392b3fa3edcc594bd7b77c2c07f9c81eed9cc92d06"},"id":"d22cccfb-9c95-4d97-aa38-893844a2a054","version":3}

**Comment by lvshtwl** [comment]
已找到问题，要假如so库。希望imtoken再readme里面写清楚。找了半天才定位到问题

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by matteozero** [comment]
> 已找到问题，要假如so库。希望imtoken再readme里面写清楚。找了半天才定位到问题

请问so库在哪里？
